/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as PassesRouteImport } from './routes/passes'
import { Route as ClearanceRouteImport } from './routes/clearance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PassesRoute = PassesRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearanceRoute = ClearanceRouteImport.update({
  id: '/clearance',
  path: '/clearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clearance': typeof ClearanceRoute
  '/passes': typeof PassesRoute
  '/requests': typeof RequestsRouteWithChildren
  '/visitors': typeof VisitorsRoute
  '/requests/new': typeof RequestsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clearance': typeof ClearanceRoute
  '/passes': typeof PassesRoute
  '/requests': typeof RequestsRouteWithChildren
  '/visitors': typeof VisitorsRoute
  '/requests/new': typeof RequestsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clearance': typeof ClearanceRoute
  '/passes': typeof PassesRoute
  '/requests': typeof RequestsRouteWithChildren
  '/visitors': typeof VisitorsRoute
  '/requests/new': typeof RequestsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/clearance'
    | '/passes'
    | '/requests'
    | '/visitors'
    | '/requests/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/clearance'
    | '/passes'
    | '/requests'
    | '/visitors'
    | '/requests/new'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/clearance'
    | '/passes'
    | '/requests'
    | '/visitors'
    | '/requests/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ClearanceRoute: typeof ClearanceRoute
  PassesRoute: typeof PassesRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  VisitorsRoute: typeof VisitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passes': {
      id: '/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof PassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clearance': {
      id: '/clearance'
      path: '/clearance'
      fullPath: '/clearance'
      preLoaderRoute: typeof ClearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof RequestsRoute
    }
  }
}

interface RequestsRouteChildren {
  RequestsNewRoute: typeof RequestsNewRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsNewRoute: RequestsNewRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ClearanceRoute: ClearanceRoute,
  PassesRoute: PassesRoute,
  RequestsRoute: RequestsRouteWithChildren,
  VisitorsRoute: VisitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
